export default {
    name: 'career',
    title: 'Career',
    type: 'document',
    fields: [
      {
        name: 'title',
        title: 'Title',
        type: 'string',
      },
      {
        title: 'Industry',
        name: 'industry',
        type: 'array',
        of: [{type: 'string'}],
        options: {
          list: [
            { title: 'Advertising + Marketing', value: 'advertising' },
            { title: 'Amusement + Recreation ', value: 'amusement' },
            { title: 'Animation + VFX', value: 'animation' },
            { title: 'Architecture', value: 'architecture' },
            { title: 'Arts + Culture', value: 'arts' },
            { title: 'Craft + Antiques', value: 'craft' },
            { title: 'Education + Research', value: 'education' },
            { title: 'Fashion + Textiles', value: 'fashion' },
            { title: 'Film / Photo / TV / Video / Radio', value: 'film' },
            { title: 'Food', value: 'food' },
            { title: 'Gaming + Interactive Media', value: 'gaming' },
            { title: 'Government + Civic + Social Services', value: 'government' },
            { title: 'Healthcare', value: 'healthcare' },
            { title: 'Manufacturing + Engineering', value: 'manufacturing' },
            { title: 'Museums + Galleries', value: 'museums' },
            { title: 'Performing Arts', value: 'performing-arts' },
            { title: 'Music', value: 'music' },
            { title: 'Publishing + Print', value: 'publishing' },
            { title: 'Technology', value: 'technology' },
            { title: 'All', value: 'all' },
          ],
        },
      },
      
      {
        title: 'Skills',
        name: 'skills',
        type: 'array',
        of: [{type: 'string'}],
        options: {
          list: [
            { title: 'Animate', value: 'animate' },
            { title: 'Build', value: 'build' },
            { title: 'Carve', value: 'carve' },
            { title: 'Capture', value: 'capture' },
            { title: 'Curate', value: 'curate' },
            { title: 'Critique', value: 'critique' },
            { title: 'Code', value: 'code' },
            { title: 'Composite', value: 'composite' },
            { title: 'Compose', value: 'compose' },
            { title: 'Conceptualize', value: 'conceptualize' },
            { title: 'Colour', value: 'colour' },
            { title: 'Cut', value: 'cut' },
            { title: 'Doodle', value: 'coodle' },
            { title: 'Draw or Sketch', value: 'draw' },
            { title: 'Design', value: 'design' },
            { title: 'Direct', value: 'direct' },
            { title: 'Document or Record (sound or images)', value: 'document' },
            { title: 'Edit (images and/or audio)', value: 'edit' },
            { title: 'Etch or Engrave', value: 'etch' },
            { title: 'Exhibit', value: 'exhibit' },
            { title: 'Experiment', value: 'experiment' },
            { title: 'Engage Communities', value: 'engage' },
            { title: 'Entertain', value: 'entertain' },
            { title: 'Fabricate', value: 'fabricate' },
            { title: 'Facilitate and/or Teach', value: 'facilitate' },
            { title: 'Film or Cinematize', value: 'film' },
            { title: 'Hack and/or Repair', value: 'hack' },
            { title: 'Imagine', value: 'imagine' },
            { title: 'Illustrate', value: 'illustrate' },
            { title: 'Ink', value: 'ink' },
            { title: 'Inform', value: 'inform' },
            { title: 'Light', value: 'light' },
            { title: 'Mold and Cast', value: 'mold' },
            { title: 'Narrative / World Build', value: 'narrative' },
            { title: 'Paint', value: 'paint' },
            { title: 'Perform', value: 'perform' },
            { title: 'Photograph', value: 'photograph' },
            { title: 'Pitch or Present', value: 'pitch' },
            { title: 'Print', value: 'print' },
            { title: 'Predict', value: 'predict' },
            { title: 'Prototype', value: 'prototype' },
            { title: 'Produce', value: 'produce' },
            { title: 'Publish', value: 'publish' },
            { title: 'Research', value: 'research' },
            { title: 'Sew', value: 'sew' },
            { title: 'Solve', value: 'solve' },
            { title: 'Strategize', value: 'strategize' },
            { title: 'Test', value: 'test' },
            { title: 'Tinker (with electronics)', value: 'tinker' },
            { title: 'Theorize', value: 'theorize' },
            { title: 'Visualize', value: 'visualize' },
            { title: 'Vectorize', value: 'vectorize' },
            { title: 'Weld', value: 'weld' },
            { title: 'Wheelthrow or Handbuild', value: 'wheelthrow' },
            { title: 'Woodwork', value: 'woodwork' },
            { title: 'Write', value: 'write' },
            { title: 'Question', value: 'question' },
            { title: '3D Model/Print', value: '3d' },
            { title: 'All', value: 'all' }
  
          ],
        },
      },

      {
        title: 'Values',
        name: 'values',
        type: 'array',
        of: [{type: 'string'}],
        options: {
          list: [
            { title: 'Flexibility', value: 'flexibility' },
            { title: 'Learning', value: 'learning' },
            { title: 'Beauty', value: 'beauty' },
            { title: 'Humor', value: 'humor' },
            { title: 'Justice', value: 'justice' },
            { title: 'Community', value: 'community' },
            { title: 'Social Responsibility', value: 'social-responsibility' },
            { title: 'Generosity', value: 'generosity' },
            { title: 'Innovation', value: 'innovation' },
            { title: 'Leadership', value: 'leadership' },
            { title: 'Financial Security', value: 'financial-security' },
            { title: 'High-Pay', value: 'high-pay' },
            { title: 'Teamwork', value: 'teamwork' },
            { title: 'Fast-Paced', value: 'fast-paced' },
            { title: 'Freedom', value: 'freedom' },
            { title: 'Unpredictable', value: 'unpredictable' },
            { title: 'Structure/Routine', value: 'structure' },
            { title: 'Helping Others', value: 'helping-others' },
            { title: 'Results Oriented', value: 'results-oriented' },
            { title: 'Process Driven', value: 'process-driven' },
            { title: 'Being Reflective', value: 'being-reflective' },
            { title: 'Being Involved in Decision-Making', value: 'decision-making' },
            { title: 'Each Day is Different', value: 'day-different' },
            { title: 'Each Day is Structured the Same', value: 'day-structured' },
            { title: 'Working Indoors', value: 'working-indoors' },
            { title: 'Working Outdoors', value: 'working-outdoors' },
            { title: 'Working with People', value: 'working-with-people' },
            { title: 'Working with Nature/Animals', value: 'working-with-nature' },
            { title: 'Working with Data (ex, ideas, words, numbers)', value: 'working-with-data' },
            { title: 'Working with Things (ex. materials, equipment, etc.)', value: 'working-with-things'},
            { title: 'All', value: 'all' },
  
          ],
        },
      },

    ],
  
    preview: {
      select: {
        title: 'title',
        author: 'author.name',
        media: 'mainImage',
      },
      prepare(selection) {
        const {author} = selection
        return Object.assign({}, selection, {
          subtitle: author && `by ${author}`,
        })
      },
    },
  }
  